<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Projects</name>
   <tag></tag>
   <elementGuidId>4abc7bae-dc12-42c4-983f-2a1777659615</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-projects</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-projects']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d823893-68af-41a4-882f-b295775c17aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app.shortlyst.ai/sourcing/jobs</value>
      <webElementGuid>3095f632-3978-431f-87ee-4f62dba05ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-projects</value>
      <webElementGuid>cddef33b-000b-4e26-b401-3e2f9e0a33d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link pt-xxl-3 pb-xxl-2</value>
      <webElementGuid>620ad45a-d91d-497a-9352-df31d7e0d143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Projects</value>
      <webElementGuid>708b709c-08c1-4313-8c2f-4d5cb55df092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-projects&quot;)</value>
      <webElementGuid>5cd94355-d218-4c22-a21c-c82ee8bdf628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu-projects']</value>
      <webElementGuid>3cccee25-42fd-42c2-8d7b-1994b25719e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarTogglerDemo01']/ul/li[2]/a</value>
      <webElementGuid>b57457b6-8db6-4039-80fa-a535fbb2e71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Projects')]</value>
      <webElementGuid>f5c7dcd7-04b6-4494-a408-2dc407a09e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>80f1892f-90c2-44d7-9a77-bcdf591841f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integration'])[1]/preceding::a[2]</value>
      <webElementGuid>fa3e43fb-5c33-472c-a4d4-5b352eaa10b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Projects']/parent::*</value>
      <webElementGuid>4c1cc274-28f9-4ac1-9c4c-f4bbd8e44f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://app.shortlyst.ai/sourcing/jobs')]</value>
      <webElementGuid>44e716c2-9b67-4830-bae5-b1a371f513ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>801044f3-da7c-4ffc-aab6-9ecbb0e04ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://app.shortlyst.ai/sourcing/jobs' and @id = 'menu-projects' and (text() = ' Projects' or . = ' Projects')]</value>
      <webElementGuid>d2d2d536-219a-434f-8ddf-b9a900ab4361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
