<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__project_name</name>
   <tag></tag>
   <elementGuidId>4bffea35-6062-41b4-9d00-7c7c9030702f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#project_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='project_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3915ca72-57b1-482d-a463-fec4d53a8aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d732352b-049c-4314-971a-ecf4e9109399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>project_name</value>
      <webElementGuid>700928d2-8550-487d-bf45-7b85cf5aa3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Project Name</value>
      <webElementGuid>8adef9d9-7e24-47a1-9701-17ba6ea3937b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f16cf44b-b90f-475e-9304-ee6162296128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project_name&quot;)</value>
      <webElementGuid>576d25e3-4fb1-4cfc-aaaa-782b882f27b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='project_name']</value>
      <webElementGuid>9eba13c9-f2fe-41a4-98ef-2131245dd489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/div/div[2]/span/form/span/div/input</value>
      <webElementGuid>4f24d5a1-e27b-4edb-aca6-e08ae10941f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span/form/span/div/input</value>
      <webElementGuid>948d87b2-36a5-49da-bb26-f50fa23390fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'project_name' and @placeholder = 'Project Name']</value>
      <webElementGuid>e0df1b5b-2d6d-41b9-84ca-2c21376187d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
